<table style="width: 100%">
    <tr style="background: #ffffff">
        <td style="width: 100%">
            <div style="text-align:right; width: 100%; text-align:right"><font style="font-size:38px"><b>Übung 3.1: Loading Data</b></font></div>
            <div style="padding-top:0px; width: 100%; text-align:right"><font size="4"><b>Programmierübung 2</b></font></div>
        </td>
    </tr>
</table>


# Loading, displaying and saving data
## Aim of this unit
Learn how to work with typical data formats in the field of medical, health and sports technology. Typical data formats are e.g. .csv and .txt files. In order to work with and process the data in the following exercises, the following skills must first be learned:
1. loading data + different data formats 
     - Numpy arrays
     - Pandas dataframes
     - Lists
2. Working with pandas
     -  Structure of dataframes
     -  Storing and Loading CSV-Files
     -  Advanced pandas
     -  Group by
     -  Operations on columns
     -  Creating new columns
     -  Simple analysis
3. Graphing data
     - Matplotlib
4. Tasks:
      1. Pandas
      2. Matplotlib

<table style="width: 100%">
    <tr style="background: #ffffff">
        <td style="width: 100%">
            <div style="text-align:right; width: 100%; text-align:right"><font style="font-size:38px"><b>1. Loading Data</b></font></div>
            <div style="padding-top:0px; width: 100%; text-align:right"><font size="4"><b>Programmierübung 2</b></font></div>
        </td>
    </tr>
</table>



# Loading data + Different data formats

Importing the used libraries
By "import numpy as np" we can call e.g. numpy functions via _numpy.functionsName_.

In [1]:
import numpy as np
import pandas as pd
import os

## Task 1.1
__Load one .csv and one .txt file each from the "ECG_Data" folder and save the file in one variable each of type Numpy Array, List and Pandas Dataframe.__

In [3]:
# define path using a string value
directory =  'EKG_Data/'
file_name = "01_Ruhe.txt"
file_name_csv = "01_Ruhe.csv"


## Open the file using the path and define a certain split character
# The files first column are Values in millivolt, second column is time in milliseconds
## Write it into a ... 
# List 
list_01 = open(directory + file_name,"r").read().split("\n")

In [ ]:
list_01[0].split("\t")

['309', '13666']

✍️ **Task** 

Print the first five elements of the `list_01`
- What could the `"\t"` stand for - remember `Huber, Julian`?
- what could You do to separate the time and voltage?

In [8]:
print (list_01[0:5])

['309\t13666', '307\t13668', '306\t13670', '304\t13672', '303\t13674']

In [12]:
#@title ❓ Click `Show code` in the code cell to show the solution. { display-mode: "form" }

print(list_01[0:5])
list_01[0].split("\t")

['309\t13666', '307\t13668', '306\t13670', '304\t13672', '303\t13674']

['309', '13666']

In [15]:
# Looping the list to split the data in two separate lists
time = []
value = []

for line in list_01:
    _line = line.split("\t")
    value.append(int(_line[0]))
    time.append(int(_line[1]))
    
print("list_01 is of type:" +  str(type(list_01)))
print("time is of type:" +  str(type(time)))
print("value is of type:" +  str(type(value)))

list_01 is of type:<class 'list'>
time is of type:<class 'list'>
value is of type:<class 'list'>

In [17]:
value

[309,
 307,
 306,
 304,
 303,
 301,
 299,
 298,
 297,
 296,
 295,
 294,
 293,
 292,
 291,
 291,
 290,
 289,
 288,
 288,
 287,
 287,
 287,
 286,
 286,
 286,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 286,
 286,
 286,
 287,
 287,
 287,
 287,
 288,
 288,
 288,
 289,
 289,
 290,
 290,
 291,
 292,
 292,
 293,
 294,
 294,
 295,
 296,
 297,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 310,
 311,
 313,
 313,
 314,
 315,
 317,
 318,
 319,
 320,
 321,
 321,
 322,
 323,
 324,
 325,
 325,
 326,
 326,
 327,
 327,
 328,
 327,
 327,
 327,
 327,
 327,
 326,
 326,
 325,
 325,
 324,
 323,
 322,
 321,
 320,
 318,
 317,
 316,
 315,
 313,
 312,
 311,
 309,
 308,
 306,
 305,
 304,
 302,
 301,
 300,
 298,
 297,
 296,
 295,
 294,
 293,
 292,
 291,
 290,
 290,
 289,
 288,
 287,
 287,
 286,
 286,
 286,
 285,
 285,
 285,
 284,
 284,
 283,
 283,
 283,
 283,
 283,
 282,
 283,
 282,
 283,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 285,
 286,
 286,
 286,
 286,
 286,
 286,
 286,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 289,
 289,
 289,
 289,
 289,
 290,
 290,
 290,
 291,
 291,
 292,
 292,
 293,
 293,
 293,
 294,
 294,
 295,
 295,
 295,
 295,
 296,
 296,
 297,
 297,
 298,
 299,
 299,
 299,
 300,
 300,
 301,
 301,
 301,
 301,
 301,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 301,
 301,
 301,
 301,
 301,
 300,
 300,
 300,
 300,
 299,
 299,
 298,
 298,
 298,
 298,
 297,
 297,
 297,
 297,
 297,
 297,
 296,
 296,
 296,
 296,
 296,
 296,
 296,
 296,
 295,
 295,
 294,
 294,
 294,
 293,
 293,
 293,
 295,
 297,
 299,
 303,
 308,
 315,
 321,
 329,
 337,
 346,
 354,
 361,
 367,
 371,
 375,
 377,
 378,
 377,
 377,
 376,
 374,
 372,
 369,
 366,
 363,
 359,
 356,
 354,
 350,
 347,
 344,
 341,
 338,
 335,
 331,
 329,
 326,
 323,
 321,
 318,
 316,
 313,
 312,
 309,
 308,
 306,
 304,
 302,
 301,
 299,
 297,
 296,
 295,
 294,
 292,
 292,
 291,
 289,
 289,
 288,
 287,
 287,
 286,
 285,
 285,
 284,
 284,
 284,
 284,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 284,
 284,
 285,
 285,
 285,
 285,
 286,
 286,
 286,
 287,
 288,
 288,
 289,
 289,
 290,
 291,
 291,
 292,
 293,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 304,
 305,
 306,
 307,
 308,
 310,
 311,
 312,
 313,
 314,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 322,
 323,
 324,
 324,
 325,
 325,
 326,
 326,
 326,
 327,
 326,
 326,
 326,
 326,
 325,
 325,
 324,
 323,
 323,
 322,
 321,
 319,
 318,
 318,
 316,
 315,
 314,
 313,
 311,
 310,
 308,
 307,
 306,
 304,
 303,
 302,
 300,
 299,
 298,
 296,
 296,
 294,
 293,
 292,
 291,
 291,
 290,
 289,
 288,
 288,
 287,
 286,
 286,
 285,
 285,
 284,
 284,
 284,
 283,
 283,
 283,
 283,
 283,
 282,
 282,
 282,
 282,
 282,
 281,
 281,
 282,
 282,
 282,
 281,
 281,
 281,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 283,
 282,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 285,
 285,
 285,
 285,
 285,
 285,
 286,
 286,
 286,
 286,
 286,
 286,
 286,
 286,
 287,
 287,
 287,
 287,
 287,
 288,
 288,
 288,
 288,
 288,
 288,
 289,
 289,
 289,
 289,
 290,
 290,
 291,
 291,
 291,
 292,
 292,
 293,
 293,
 294,
 294,
 294,
 295,
 295,
 295,
 295,
 296,
 297,
 297,
 297,
 298,
 298,
 299,
 299,
 300,
 300,
 301,
 301,
 301,
 301,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 302,
 301,
 301,
 301,
 301,
 301,
 300,
 300,
 300,
 299,
 299,
 299,
 298,
 298,
 298,
 297,
 297,
 297,
 297,
 297,
 297,
 297,
 296,
 296,
 296,
 296,
 296,
 296,
 296,
 295,
 295,
 295,
 294,
 294,
 293,
 293,
 293,
 294,
 295,
 297,
 300,
 304,
 309,
 315,
 322,
 330,
 338,
 347,
 355,
 362,
 368,
 373,
 377,
 379,
 379,
 379,
 379,
 378,
 376,
 374,
 371,
 368,
 365,
 361,
 357,
 354,
 351,
 347,
 344,
 341,
 338,
 334,
 331,
 329,
 326,
 323,
 320,
 318,
 316,
 313,
 311,
 309,
 307,
 305,
 303,
 301,
 300,
 298,
 297,
 296,
 294,
 293,
 292,
 291,
 290,
 289,
 288,
 288,
 287,
 286,
 285,
 285,
 285,
 284,
 284,
 283,
 283,
 283,
 283,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 283,
 283,
 283,
 283,
 284,
 284,
 285,
 285,
 285,
 286,
 286,
 287,
 287,
 288,
 289,
 289,
 290,
 291,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 305,
 306,
 307,
 308,
 309,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 322,
 323,
 324,
 324,
 325,
 325,
 325,
 326,
 326,
 326,
 326,
 326,
 326,
 325,
 325,
 324,
 323,
 322,
 321,
 320,
 319,
 318,
 317,
 316,
 314,
 313,
 312,
 310,
 309,
 307,
 306,
 305,
 303,
 302,
 301,
 299,
 298,
 297,
 296,
 295,
 294,
 293,
 292,
 291,
 290,
 289,
 289,
 288,
 287,
 287,
 286,
 286,
 285,
 285,
 285,
 284,
 284,
 284,
 283,
 283,
 283,
 283,
 283,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 282,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 283,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 284,
 285,
 285,
 285,
 285,
 285,
 285,
 286,
 285,
 286,
 286,
 286,
 286,
 286,
 287,
 287,
 287,
 287,
 287,
 287,
 287,
 288,
 288,
 288,
 288,
 288,
 288,
 289,
 289,
 289,
 289,
 289,
 290,
 290,
 290,
 291,
 291,
 292,
 292,
 292,
 293,
 293,
 294,
 294,
 295,
 295,
 295,
 296,
 296,
 296,
 297,
 298,
 298,
 298,
 299,
 299,
 300,
 300,
 301,
 301,
 301,
 302,
 302,
 302,
 302,
 303,
 303,
 303,
 303,
 303,
 303,
 303,
 302,
 303,
 302,
 302,
 302,
 302,
 301,
 301,
 301,
 300,
 300,
 300,
 299,
 299,
 299,
 299,
 298,
 298,
 298,
 298,
 298,
 298,
 297,
 297,
 297,
 297,
 297,
 297,
 297,
 297,
 296,
 296,
 296,
 296,
 295,
 294,
 294,
 294,
 294,
 294,
 296,
 298,
 302,
 306,
 311,
 318,
 326,
 334,
 342,
 351,
 ...]

In [18]:
# Numpy Array
array_01_test = np.array(list_01)

print("array_01_test is of type:" +  str(type(array_01_test)))
# The array is still containing the "\t" separator, instead we could use the two lists "value","time" and stack them into one array... input has to be a tupel 
array_01 = np.column_stack((time, value)) 
print("after stacking the two list in one array it is of type:" + str(type(array_01)))

array_01_test is of type:<class 'numpy.ndarray'>
after stacking the two list in one array it is of type:<class 'numpy.ndarray'>

In [19]:
array_01

array([[ 13666,    309],
       [ 13668,    307],
       [ 13670,    306],
       ...,
       [633011,    298],
       [633013,    299],
       [633015,    300]])

✍️ **Task**  

Try to load the list_01 directly into a data frame: `df_01 = pd.DataFrame(list_01)`

In [20]:
#@title ❓ Click `Show code` in the code cell to show the solution. { display-mode: "form" }
df_01 = pd.DataFrame(list_01)

In [21]:
# Pandas dataframe
print("df_01 is of type:" +  str(type(df_01)))

print("the first 5 rows of the dataframe look like this: ")
print(df_01.head())

df_01 is of type:<class 'pandas.core.frame.DataFrame'>
the first 5 rows of the dataframe look like this:
            0
0  309\t13666
1  307\t13668
2  306\t13670
3  304\t13672
4  303\t13674

In [ ]:
df_01

                  0
0        309\t13666
1        307\t13668
2        306\t13670
3        304\t13672
4        303\t13674
...             ...
304832  296\t633007
304833  297\t633009
304834  298\t633011
304835  299\t633013
304836  300\t633015

[304837 rows x 1 columns]

## Task 1.2

Notice, that the dataframe still contains the tabulator "\t" in it. There is a easier and more elegant way than using "open" and converting it into a list first.

✍️ **Task**  
Look up the pandas function __"pd.read_csv"__ and use it, to load the txt. and .csv file into a dataframe. Please also add a header with the column names :`"Amplitude in [mV]" ,"Time in [ms]"`

In [26]:
df_ruhe_01 = pd.read_csv(r"EKG_Data\01_Ruhe.csv", sep=';')
df_ruhe_01

        309   13666
0       307   13668
1       306   13670
2       304   13672
3       303   13674
4       301   13676
...     ...     ...
304831  296  633007
304832  297  633009
304833  298  633011
304834  299  633013
304835  300  633015

[304836 rows x 2 columns]

In [ ]:
#@title ❓ Click `Show code` in the code cell to show the solution. { display-mode: "form" }

df_ruhe_01 = pd.read_csv(directory + file_name, sep='\t')
print(df_ruhe_01.head())

# for csv file
column_names = ["Amplitude in [mV]" ,"Time in [ms]"]
df_ruhe_01_csv = pd.read_csv(directory + file_name_csv, sep=';',header=None, names= column_names)
df_ruhe_01_csv.head()

   309  13666
0  307  13668
1  306  13670
2  304  13672
3  303  13674
4  301  13676

   Amplitude in [mV]  Time in [ms]
0                309         13666
1                307         13668
2                306         13670
3                304         13672
4                303         13674

## Task 1.3

The pandas built-in loading function is very powerful, since it can be modified by multiple input parameters in the function.

✍️ **Task** 
Use the function with all its capabilities, given the following csv file __TrackManData__ in the Data folder. The goal is to extract the ```Attack Angle, Ball Speed, Impact Offset, Impact Height and the Tags```. Please use following parameters ```ep, header, usecols, skiprow``` to delete the first (0) row and use the second (1) row as header. Also the row, containing the units for the data, should be deleted.

In [27]:
#@title ❓ Click `Show code` in the code cell to show the solution. { display-mode: "form" }

path = 'Data/TrackManData.csv'
column_names = ["Date" ,"Ball Speed","Attack Angle", "Impact Offset", "Impact Height", "Tags"]
df = pd.read_csv(path, sep=',', header=1, usecols= column_names, skiprows=[2])
df

FileNotFoundError: [Errno 2] No such file or directory: 'Data/TrackManData.csv'

# 🏁 Recap Loading Data

- If you have finished the tasks and have no questions, start with the exercice provided on SAKAI.
- If you have finished the tasks but would like to discuss the solutions together again, please tell your teacher!

<table style="width: 100%">
    <tr style="background: #ff9900">
        <td style="width: 100%">
            <div style="text-align:center; width: 100%; text-align:center"><font style="font-size:38px"><b>Good Job!</b></font></div>
            <div style="padding-top:0px; width: 100%; text-align:right"><font size="4"><b>SoSe 2023</b></font></div>
        </td>
    </tr>
</table>